import type { RuleConfig } from './types.ts'

/**
 * Editable scoring/rules configuration.
 * Weights are starting points, not final truth. Change here or via PUT /api/config/rules.
 */
export const DEFAULT_RULE_CONFIG: RuleConfig = {
  version: 1,
  notes:
    'Initial editable weights. Do not treat scores as ground truth. Unknown data stays UNKNOWN.',
  scoring: {
    baseScore: 50,
    minScore: 0,
    maxScore: 100,
    highScoreThreshold: 70,
    weights: {
      agePreference: 10,
      proximity: 12,
      mexicoBonus: 8,
      cdmxBonus: 10,
      catholicBonus: 8,
      practicingCatholicBonus: 8,
      traditionalValuesBonus: 6,
      seriousRelationshipBonus: 7,
      neverMarriedBonus: 8,
      singleDeclaredBonus: 4,
      noChildrenBonus: 10,
      verifiedBonus: 5,
      childrenPenalty: 25,
      separatedPenalty: 12,
      contradictoryProfilePenalty: 10,
      suspiciousProfilePenalty: 18,
      scamSignalsPenalty: 30,
      incompleteCriticalInformationPenalty: 8,
    },
    age: {
      adultMin: 18,
      preferredMin: 28,
      preferredMax: 42,
      acceptableMin: 24,
      acceptableMax: 48,
    },
    proximity: {
      preferredMaxKm: 80,
      acceptableMaxKm: 400,
    },
    mexicoCountryMatches: ['mexico', 'méxico', 'mx', 'mex'],
    cdmxLocationMatches: [
      'cdmx',
      'ciudad de mexico',
      'ciudad de méxico',
      'mexico city',
      'méxico city',
      'df',
      'distrito federal',
      'estado de mexico',
      'estado de méxico',
      'edomex',
      'naucalpan',
      'tlalnepantla',
      'ecatepec',
      'nezahualcoyotl',
      'nezahualcóyotl',
      'satelite',
      'satélite',
      'coyoacan',
      'coyoacán',
      'polanco',
      'condesa',
      'roma norte',
      'roma sur',
      'del valle',
      'santa fe',
      'interlomas',
      'tecámac',
      'tecamac',
      'cuajimalpa',
      'miguel hidalgo',
      'benito juarez',
      'benito juárez',
    ],
    catholicMatches: ['catholic', 'católica', 'catolica', 'católico', 'catolico'],
    practicingMatches: [
      'practicing',
      'practising',
      'practicante',
      'practica su fe',
      'practica la fe',
      'mass',
      'misa',
      'church every',
      'iglesia',
    ],
    traditionalValuesMatches: [
      'traditional values',
      'valores tradicionales',
      'family oriented',
      'family-oriented',
      'orientada a la familia',
      'familia tradicional',
      'faith and family',
      'fe y familia',
      'old fashioned',
      'conservative',
      'conservadora',
    ],
    seriousRelationshipMatches: [
      'serious relationship',
      'relación seria',
      'relacion seria',
      'marriage',
      'matrimonio',
      'long-term',
      'largo plazo',
      'life partner',
      'compañero de vida',
      'companero de vida',
      'looking for something real',
      'algo serio',
    ],
    scamSignalMatches: [
      'western union',
      'send money',
      'investment opportunity',
      'whatsapp only',
      'telegram only',
      'crypto gift',
      'leave this site',
      'gift card',
    ],
    agencySignalMatches: [
      'translation team',
      'agency profile',
      'we can introduce',
      'international dating club',
    ],
    botSignalMatches: [
      'copy-paste template',
      'generic greeting only',
      'lorem ipsum',
    ],
    suspiciousBioMatches: [
      'send money',
      'lonely military',
      'widowed oil engineer',
      'cannot receive messages here',
    ],
  },
}
